//! The fixture harness: runs [`texbib::parse`] against every `fixtures/<name>/main.bib` that has
//! an `expected.json` beside it and checks two things — that the parsed items match, and that
//! the items' spans reproduce the input byte for byte. Each `#[test]` below this module's own
//! code is generated by `build.rs` from the directory listing (see its doc comment, and
//! `crates/texlog/tests/fixtures.rs`, which this file is modelled on).
//!
//! This is an integration test (`tests/`, not `src/`) because it exercises the crate the way a
//! caller would, across the same boundary `lib.rs` promises: text in, data out.

use std::fs;
use std::path::Path;

/// Parse `fixtures/<name>/main.bib` and compare it, as JSON, against `expected.json`.
///
/// Comparing parsed [`serde_json::Value`]s rather than text means key order and whitespace in a
/// hand-edited `expected.json` never matter, and a mismatch pretty-prints what the parser
/// actually produced, ready to paste in when the change was intended. Start a new fixture with
/// an `expected.json` of `[]` to get that output.
fn run_fixture(name: &str) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures").join(name);

    let source = fs::read_to_string(dir.join("main.bib"))
        .unwrap_or_else(|e| panic!("{name}: could not read main.bib: {e}"));
    let expected_text = fs::read_to_string(dir.join("expected.json"))
        .unwrap_or_else(|e| panic!("{name}: could not read expected.json: {e}"));
    let expected: serde_json::Value = serde_json::from_str(&expected_text)
        .unwrap_or_else(|e| panic!("{name}: expected.json is not valid JSON: {e}"));

    let bib = texbib::parse(&source);

    // The round-trip property first: it is the one a wrong fixture is least likely to have
    // captured by hand, and the one later loops' in-place edits depend on.
    let mut rebuilt = String::new();
    let mut next_start = 0;
    for item in &bib.items {
        let span = item.span();
        assert_eq!(span.start, next_start, "{name}: gap or overlap in spans before {item:?}");
        rebuilt.push_str(span.text(&source));
        next_start = span.end;
    }
    assert_eq!(rebuilt, source, "{name}: concatenated item spans do not reproduce the input");

    let found_json = serde_json::to_value(&bib.items).expect("items always serialise");
    assert_eq!(
        found_json,
        expected,
        "{name}: parsed items did not match expected.json.\n\
         If this is a new or intentionally changed fixture, this is the expected.json to write:\n{}",
        serde_json::to_string_pretty(&found_json).unwrap()
    );
}

include!(concat!(env!("OUT_DIR"), "/fixture_tests.rs"));
